#syntax=docker/dockerfile:1.2
FROM zwallet_builder_linux AS builder

ENV PATH $PATH:/flutter/bin:/root/.cargo/bin

COPY . /zwallet

RUN cd /zwallet/native/zcash-sync && cargo build --release --features=dart_ffi
RUN cd /zwallet && ./build-linux.sh
RUN cd /zwallet/build/linux/x64/release/bundle && tar cvzf /zwallet.tgz *

FROM alpine:latest
WORKDIR /root
COPY --from=builder /zwallet.tgz ./
COPY --from=builder /zwallet/target/release/libwarp_api_ffi.so ./

