#syntax=docker/dockerfile:1.2
FROM archlinux:base-devel-20220227.0.49015 AS builder

COPY install-deps.sh .

RUN ./install-deps.sh

FROM builder as builder2

ENV ANDROID_SDK_ROOT /Android/sdk
ENV PATH $PATH:$ANDROID_SDK_ROOT/platform-tools:/flutter/bin
ENV ANDROID_NDK_HOME $ANDROID_SDK_ROOT/ndk/21.4.7075529

COPY . /zwallet

RUN --mount=type=secret,id=pwd cd /zwallet && ./configure.sh zcash && ./build.sh

FROM alpine:latest
WORKDIR /root
COPY --from=builder2 /zwallet/build/app/outputs/bundle/release/* ./
