##syntax=docker/dockerfile:1.2
#FROM archlinux:base-devel-20220227.0.49015 AS builder_rust
#
#COPY install-rust.sh .
#RUN ./install-rust.sh
#
#FROM builder_rust as builder_flutter
#
#COPY install-deps.sh .
#RUN --mount=type=cache,target=/tmp ./install-deps.sh
#
#ENV ANDROID_SDK_ROOT /root/Android/sdk
#ENV PATH $PATH:$ANDROID_SDK_ROOT/platform-tools:/root/flutter/bin
#ENV ANDROID_NDK_HOME $ANDROID_SDK_ROOT/ndk/21.4.7075529

# FROM builder_flutter as builder_zwallet
FROM hhanh00/builder_zwallet as builder

ENV ANDROID_SDK_ROOT /root/Android/sdk
ENV ANDROID_NDK_HOME $ANDROID_SDK_ROOT/android-ndk-r21e
ENV PATH $PATH:$ANDROID_SDK_ROOT/platform-tools:/root/flutter/bin

COPY . /zwallet

RUN git config --global --add safe.directory /root/flutter
RUN --mount=type=secret,id=pwd cd /zwallet && ./configure.sh zcash && ./build.sh

FROM alpine:latest
WORKDIR /root
COPY --from=builder /zwallet/build/app/outputs/flutter-apk/app-release.apk ./
