[package]
name = "rust_lib_YWallet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.9.0"
anyhow = "1"
reqwest = { version = "0.11.27", features = ["json"] }
zcash-vote = { path = "../native/zcash-vote" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
