// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

Future<Election> createElection(
        {required String filepath,
        required String urls,
        required String key}) =>
    RustLib.instance.api
        .crateApiSimpleCreateElection(filepath: filepath, urls: urls, key: key);

@freezed
class Election with _$Election {
  const factory Election({
    required String name,
    required int startHeight,
    required int endHeight,
    required String question,
    required List<String> candidates,
    required bool signatureRequired,
  }) = _Election;
}
