name: Build and Release Linux AppImage/Flatpak

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    if: "!contains(github.head_ref, 'release-please--')"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: env
        run: |
          cat build.env >> $GITHUB_ENV
          echo $PWD/flutter/bin >> $GITHUB_PATH

      - name: Build
        run: ./build-scripts/build-linux.sh "${{ env.FLUTTER_VERSION }}"

      - name: appimage
        run: ./build-scripts/build-appimage.sh

      - name: Flatpak
        run: |
          docker build -f docker/Dockerfile-flatpak -t zwallet_flatpak_sh .
          docker run --privileged --name zwallet_flatpak_bin zwallet_flatpak_sh
          docker cp zwallet_flatpak_bin:/root/misc/ywallet.flatpak .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./misc/Ywallet-latest-x86_64.AppImage
            ./ywallet.flatpak
            ./zwallet.tgz
            ./libwarp_api_ffi.so

      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: ./misc/Ywallet-latest-x86_64.AppImage
          retention-days: 3
